---
# tasks file for dependencies
- name: Install dependencies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - gnupg-agent
